[package]
name = "smashlang"
version = "0.1.0"
edition = "2021"

[dependencies]
inkwell = { version = "0.2.0", features = ["llvm15-0"], optional = true }
anyhow = "1.0"
rustyline = "11.0.0"  # For improved REPL input handling
colored = "2.0.0"    # For colored terminal output

[features]
default = []
compiler = ["inkwell"]

[lib]
name = "smashlang"
path = "src/lib.rs"

[[bin]]
name = "smash"
path = "src/main.rs"
